[build]
  command = "pnpm build"
  publish = "dist/static"
  functions = "netlify/functions"

[dev]
  command = "pnpm dev:client"
  targetPort = 3000
  port = 8888
  publish = "dist/static"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
